{% set name = "isal" %}
{% set version = "0.4.0" %}

package:
  name: python-isal    # To avoid confusion with isa-l proper
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c1b132ddabbf698ba44811d65bb8e8effb8872425f8735a4b767949148bfbb0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHON_ISAL_LINK_DYNAMIC=true  # Forces a dynamic link against isa-l in conda-forge
  # isa-l package only available on linux as of yet.
  skip: true  # [not unix]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - isa-l
    - python
    - pip
    - cython  # Cython and setuptools are also required in pyproject.toml
    - setuptools 
  run:
    - python
    - isa-l >=2.26
test:
  imports:
    - isal
  commands:
    - python -c "from isal import igzip"
    - python -c "from isal import isal_zlib; isal_zlib.adler32(b'test')"

about:
  home: https://github.com/pycompression/python-isal
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Faster zlib and gzip compatible compression and decompression by providing python bindings for the isa-l library.
  doc_url: https://python-isal.readthedocs.io
  dev_url: https://github.com/pycompression/python-isal

extra:
  recipe-maintainers:
    - rhpvorderman
